### ISSUE TITLE
Validate youtube URL input

### ISSUE THREAD

**Issue by craigspaeth** [craigspaeth/astral-projection#58]
On keyup we should make sure a Youtube URL is valid, and if not, render a quick and dirty `<small>Invalid youtube URL</small>` underneath it (full UI design coming later).

**Comment by JGYaniv** [comment]
On it!

**Comment by JGYaniv** [comment]
Do we want to actually check if the link is pointing to a working youtube page or just if it is a correctly formatted youtube url?

ie
valid formatting, not a working page: https://www.youtube.com/watch?v=qrpKugAwHc4
valid formatting, working page: https://www.youtube.com/watch?v=qrpKugAwHc4
invalid formatting: https://www.notyoutube.com/watch?v=nothanks
